version: "3.8"

services:
  eureka:
    image: "eureka-server"
    container_name: eureka-server
    build:
      context: ./eureka-server
    ports:
      - "8761:8761"

  user-ms-app:
    container_name: user-ms-app
    image: 'user-ms-app:latest'
    build:
      context: ./userMS
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:8761/eureka
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-user-db:5433/user
    ports:
      - "8080:8080"
    depends_on:
      - postgres-user-db
      - eureka
    links:
      - postgres-user-db
      - eureka

  auth-ms-app:
    container_name: auth-service-app
    image: "auth-service-app:latest"
    build:
      context: ./auth-service
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:8761/eureka
    ports:
      - "8081:8081"
    depends_on:
      - eureka
    links:
      - eureka

  gateway:
    image: "gateway"
    container_name: gateway
    build:
      context: ./gateway
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:8761/eureka
    ports:
      - "8082:8082"
    depends_on:
      - eureka

  project-ms-app:
    container_name: project-ms-app
    image: 'project-ms-app:latest'
    build:
      context: ./projectMS
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:8761/eureka
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-project-db:5434/project
    ports:
      - "8083:8083"
    depends_on:
      - postgres-project-db
      - eureka
    links:
      - postgres-project-db
      - eureka

  event-ms-app:
    container_name: event-ms-app
    image: 'event-ms-app:latest'
    build:
      context: ./eventMS
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:8761/eureka
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-event-db:5435/event
    ports:
      - "8084:8084"
    depends_on:
      - postgres-event-db
      - eureka
    links:
      - postgres-event-db
      - eureka

  account-ms-app:
    container_name: account-ms-app
    image: 'account-ms-app:latest'
    build:
      context: ./accountMS
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:8761/eureka
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-account-db:5436/account
    ports:
      - "8085:8085"
    depends_on:
      - postgres-account-db
      - eureka
    links:
      - postgres-account-db
      - eureka

  task-ms-app:
    container_name: task-ms-app
    image: 'task-ms-app:latest'
    build:
      context: ./taskMS
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:8761/eureka
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-task-db:5437/task
    ports:
      - "8086:8086"
    depends_on:
      - postgres-task-db
      - eureka
    links:
      - postgres-task-db
      - eureka

  postgres-user-db:
    container_name: postgres-user-db
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: user
    command: -p 5433
    ports:
      - "5433:5433"

  postgres-project-db:
    container_name: postgres-project-db
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: project
    command: -p 5434
    ports:
      - "5434:5434"

  postgres-event-db:
    container_name: postgres-event-db
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: event
    command: -p 5435
    ports:
      - "5435:5435"

  postgres-account-db:
    container_name: postgres-account-db
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: account
    command: -p 5436
    ports:
      - "5436:5436"

  postgres-task-db:
    container_name: postgres-task-db
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: task
    command: -p 5437
    ports:
      - "5437:5437"


